name: Build MAUI Android APK

on:
  push:
    branches: [ master ]   # Runs when commits are pushed to main
  workflow_dispatch:      # Optional manual trigger via GitHub UI

jobs:
  build-android-apk:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build .NET MAUI Android APK
      run: dotnet publish -f net9.0-android -c Release -o ./soko_pub

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MAUI-APK
        path: ./soko_pub/*.apk
